<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Shared.props" />
	
  <PropertyGroup>
    <AssemblyName>JetFlow.Abstractions</AssemblyName>
    <RootNamespace>JetFlow</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>JetFlow.Core</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>JetFlow.Observability</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>JetFlow.Testing</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
