<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Shared.props" />

	<PropertyGroup>
		<AssemblyName>JetFlow.Observability</AssemblyName>
		<RootNamespace>JetFlow</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NATS.Net" Version="3.1.0" />
	</ItemGroup>

</Project>
