<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Shared.props" />

	<PropertyGroup>
		<AssemblyName>JetFlow.Observability</AssemblyName>
		<RootNamespace>JetFlow</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
		<ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(TargetDir)JetFlow.Common.dll" Pack="true" PackagePath="lib/$(TargetFramework)" />
	</ItemGroup>

</Project>
