<Project Sdk="Microsoft.NET.Sdk">
	
	<Import Project="../Shared.props" />
	
  <PropertyGroup>
	  <AssemblyName>JetFlow.Core</AssemblyName>
	  <RootNamespace>JetFlow</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
	  <_Parameter1>JetFlow.Testing</_Parameter1>
	</AssemblyAttribute>
  </ItemGroup>

	<ItemGroup>
		<None Include="$(TargetDir)JetFlow.Common.dll" Pack="true" PackagePath="lib/$(TargetFramework)" />
	</ItemGroup>

</Project>
