<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../Shared.props" />

	<PropertyGroup>
		<AssemblyName>JetFlow.UI</AssemblyName>
		<RootNamespace>JetFlow.UI</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="WebFiles\index.html" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="WebFiles\index.html" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
	  <ProjectReference Include="..\..\Common\Common.csproj" />
	  <ProjectReference Include="..\..\Observability\Observability.csproj" />
	  <ProjectReference Include="..\Abstractions\UI.Abstractions.csproj" />
	</ItemGroup>

</Project>
